sudo: required
dist: trusty

language: node_js
node_js: 10

cache:
  yarn: true
  directories: node_modules

addons:
  chrome: stable

notifications:
  email:
    on_failure: change
    on_success: change

matrix:
  include:
    - env: MODE=lint
      script: yarn lint

    - env: MODE=deploy
      script: yarn build

      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
        project: "attack-modifier-deck"
        on:
          branch: master
